### ISSUE TITLE
Canadian provinces and USA states as territories?

### ISSUE THREAD

**Issue by baywet** [ideditor/country-coder#19]
Hi!
Great library!
I was wondering whether you were planning to add Canadian provinces and territories as well as USA states as territories (or other type of features) in the data set?

**Comment by quincylvania** [comment]
Hi @baywet, thanks so much for integrating! For background, understand that we developed country-coder to support [iD](https://github.com/openstreetmap/iD), the web editor for the global OpenStreetMap project.

The short answer is no, unfortunately we're not planning on adding subdivisions beyond those included in ISO 3166-1 and M49 😢

The only reasons for this are practical. Country-coder currently has fewer than 300 GeoJSON features. To fully support ISO 3166-2 subdivisions we'd have to add nearly 5000 more! It'd take significant time to gather and maintain the data, though the far bigger issue for our web app would be the drastically increased download size. While we could theoretically support some countries (e.g. the US and Canada) but not others, that wouldn't be particularly useful to us nor fair to our mappers around the world.

That said, it should be relatively easy to fork the code and roll your own solution. Good luck!

**Comment by peternewman** [comment]
> though the far bigger issue for our web app would be the drastically increased download size

Would it be overly complex to support multiple packs so apps could just load the ones for e.g. the countries they needed that level of detail in. Which would also mean different people/groups could spend the time contributing different countries.

> That said, it should be relatively easy to fork the code and roll your own solution. Good luck!

Packs of states or equivalent would also avoid different people duplicating that work.

**Comment by quincylvania** [comment]
> Would it be overly complex to support multiple packs so apps could just load the ones for e.g. the countries they needed that level of detail in.

It's doable, but not trivial. From my perspective, the effort and complexity are only worthwhile if the results serve the needs of iD. I could see us doing interesting things with granular-scale features eventually, but we don't have a pressing need yet.

> Packs of states or equivalent would also avoid different people duplicating that work.

If anyone makes a similar package for sub-country areas, I'd be happy to add a link to the README for others to take advantage of.

**Comment by ArloJamesBarnes** [comment]
> If anyone makes a similar package for sub-country areas

As a stopgap place to direct downstream consumers who wish to supplement countrycoder, do you think https://github.com/whosonfirst-data/whosonfirst-data-admin-ca (for example) would be appropriate?
