### ISSUE TITLE
Emoji flag for Metropolitan France is broken 

### ISSUE THREAD

**Issue by bhousel** [ideditor/country-coder#25]
https://github.com/ideditor/country-coder/blob/f7118179ba55c54d23e739918314ae12a93a6cf7/src/country-coder.ts#L226-L232

This works for most flags, but Metropolitan France uses the code `fx` which doesn't have a flag.  Maybe it should just hardcode `fr` here?

I'm not sure if there are any other countries like this.  Metropolitan France is kind of weird.

<img width="404" alt="Screenshot 2020-06-22 14 49 49" src="https://user-images.githubusercontent.com/38784/85324338-a89acc80-b497-11ea-99bf-5f314d025b54.png">
<img width="406" alt="Screenshot 2020-06-22 14 49 39" src="https://user-images.githubusercontent.com/38784/85324347-ab95bd00-b497-11ea-982e-64c4e6a20683.png">

**Comment by quincylvania** [comment]
Hmm I'm not sure if we should hardcode this or not. Emoji flags are defined by two codepoints that correspond directly to the two-letter ISO codes, so returning a different emoji changes the identity.

`FX` is one of several unofficial yet "[exceptionally reserved](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations)" codes we support in country-coder. Interestingly, the other ones have defined emojis. Some have their own symbol, like 🇮🇨 for `IC`, while others use the same rendering as the higher-level region, like [🇨🇵 for `CP`](https://emojipedia.org/flag-clipperton-island/). You'd think `FX` would work similarly, but apparently not. It's the only ISO code I can see in country-coder without a corresponding emoji flag.

With this in mind, I'm thinking country-coder's behavior is technically correct and it's up to the ISO or Unicode Consortium to figure it out. But I'm also not against hardcoding if this is causing problems.

**Comment by bhousel** [comment]
Interesting!  I found this:  https://en.wikipedia.org/wiki/Regional_Indicator_Symbol

It looks like a handful of these have been officially deprecated within CLDR, and `FX` is in that list.  (I don't think any of the other deprecations are things I would even try to use).  

I agree that country-coder's behavior is technically correct, so I'll close this and adjust the flag in the Location Conflation viewer.

**Comment by quincylvania** [comment]
@bhousel Sounds good. Countries and text encoding are both so complicated separately, it's a wonder there aren't more issues when they collide.
