### ISSUE TITLE
A few more sub-country pseudo codes

### ISSUE THREAD

**Issue by bhousel** [ideditor/country-coder#26]
This is not a high priority issue, but maybe a nice-to-have.

CountryCoder and LocationConflation are integrated into Name Suggestion Index now which is pretty cool..
Check out the entries on https://nsi.guide to see what I mean:

<img width="600" alt="Screenshot 2020-07-17 10 59 51" src="https://user-images.githubusercontent.com/38784/87800694-b46e7a00-c81c-11ea-812e-440f9f76a7d1.png">
<img width="600" alt="Screenshot 2020-07-17 11 00 03" src="https://user-images.githubusercontent.com/38784/87800719-bafcf180-c81c-11ea-8c5a-c0bea00c6611.png">

**A thing I am running into is:**
Some countries like US, GB, FR include a bunch of sub territories.  Technically the US includes Marshall Islands and GB includes Bermuda.  FR is nice because we can use the code FX to mean "Metropolitan France".   But for some situations, it would be really nice to have dedicated code strings for:
- Contiguous United States (aka lower 48) - https://en.wikipedia.org/wiki/Contiguous_United_States
- AK / HI  / US + AK + HI as separate queryable geometries
- British Isles - https://en.wikipedia.org/wiki/British_Isles
- England / Scotland / Wales / North Ireland as separate queryable geometries
- maybe others?

I'm not familiar with what all countries contain territories, and not sure to what extent Country Coder already includes some of these.. just brainstorming that it would be nice to say 'conus' or 'scotland' to return just those parts.

**Comment by quincylvania** [comment]
Hmm I see where this lack of granularity could be annoying. I'm wary of starting to add political sub-territories just because they exist (#19). But I do think adding a few regions like these that are commonly considered culturally or geographically distinct would be pretty helpful without adding much overhead. Overseas territories in particular should have their own identities.

**Comment by bhousel** [comment]
Cool - yeah I think anything that has its own Wikidata QID it's at least notable enough for inclusion, even if it doesn't have a ISO country code.

**Comment by quincylvania** [comment]
I added 100 new features in [v4.0.0](https://github.com/ideditor/country-coder/releases/tag/v4.0.0), I think we can close this. People should feel free to open new issues if they need more!
