### ISSUE TITLE
Support bbox query?

### ISSUE THREAD

**Issue by sjchristi** [ideditor/country-coder#32]
which-polygon has a bbox query, which would be amazing if you could support.  The use case is: I'm looking at a map and I want to find out all countries that are on the screen given a min/max lat,lng pairs.

Happy to attempt to add this myself, I just thought I'd make the suggestion as it will probably takes the maintainers much less time to implement.

**Comment by quincylvania** [comment]
Welcome, @sjchristi. This sounds reasonable. I could work on it at some point, but feel free to work on it yourself if you need it soon.

**Comment by quincylvania** [comment]
On second thought, this didn't seem like it would take that long so I just went ahead and did it.
