### ISSUE TITLE
ESM export broken in react-native env (non-expo)

### ISSUE THREAD

**Issue by HowardLin114** [ideditor/country-coder#45]
**react-native version: 0.64.2**

import * as countryCoder from '@ideditor/country-coder';  // ES6 import all
import { iso1A2Code } from '@ideditor/country-coder';

Neither works, it will just show as **undefined function.**

`[TypeError: undefined is not a function]`

Other exports don't work as well, I suspect something to do with your exports configuration?
import { feature, iso1A2Code, emojiFlag } from '@ideditor/country-coder'; 

I reverted back my upgrade, **the latest version of ideditor/country-coder that works in a react-native (non-expo) environment is v4.1.0**

**Comment by bhousel** [comment]
Thanks for reporting - can you double check that you are definitely using v5.0.2 (sometimes a package-lock or yarn.lock file will lock in an older non-working dependency)

I have v5.0.1 working over in the sister project https://github.com/ideditor/location-conflation , will test it with v5.0.2 tomorrow.  It's very possible that the export map has a problem.

**Comment by HowardLin114** [comment]
Thanks. I am definitely using v5.0.2, just double checked.

The specific error is (the result of calling the function iso1A2Code twice, or any function that is imported) 

```
WARN  0 [TypeError: undefined is not a function]
WARN  1 [TypeError: undefined is not a function]
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:523:3)
    at tryReadSync (fs.js:348:20)
    at Object.readFileSync (fs.js:385:19)
    at UnableToResolveError.buildCodeFrameMessage

```

"react": "^17.0.2",
"react-native": "^0.64.2",

**Comment by HowardLin114** [comment]
@bhousel Thank you very much for the help. Just one small thing left before package is fully ready for RN again.

Yes browser export was causing issues, and I get the actual root issue now aside from browser export.

**It's the file extension pattern matching.**

This is v4.1.0 package.json, it conforms to pattern

```
"main": "./dist/country-coder.js",
"module": "./dist/country-coder.module.js",
```

it conforms to this pattern that React-Native wants, notice the .js extension `(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)`, without this Xcode will not build.

However in v5.0.3, it becomes 

```
"main": "./dist/country-coder.cjs",
"module": "./dist/country-coder.mjs",
```

If I just added a .js to both of these files (RN uses module but both pattern matching was needed)

```
"main": "./dist/country-coder.cjs.js",
"module": "./dist/country-coder.mjs.js",
```

This works perfectly. All features are now back online. It's silly, but the pattern matching is strict.
