### ISSUE TITLE
France: EU + Europe missing ?

### ISSUE THREAD

**Issue by jbelien** [ideditor/country-coder#47]
I've started using `country-coder` in my [OpenStreetMap Community Viewer](https://github.com/jbelien/oci-viewer).

I'm trying to "guess" the region/continent a country is from using `country-coder` groups.
It works pretty well ... except for France (and I guess other countries in a similar "situation") !

Groups for France are `["UN", "001"]` (see https://ideditor.codes/?code=Q142).
There is definitely `EU` missing !
But I would also expect `150` (Europe) ; I guess this happens because France has territories outside Europe (same happens to Spain).

- Why is `EU` missing ? France is one of the founding member of European Union (https://en.wikipedia.org/wiki/Member_state_of_the_European_Union)
- How can I get that France (or Spain) is part of Europe (but maybe this is out of the scope of the library) ?

Thanks for this awesome library :)

**Comment by bhousel** [comment]
Weird, yeah I don't really understand it.
I do know that "Metropolitan France" with the ISO code `FX`, and is a separate feature that is within France and within Europe, EU, etc..
https://ideditor.codes/?code=Q212429
`"groups": ["FR", "155", "150", "EU", "UN", "001"],`

**Comment by bhousel** [comment]
I did some more testing today and I still don't know what's going on

```js
> import("@ideditor/country-coder").then(module => { cc = module });
Promise { <pending> }
> cc.isInEuropeanUnion('fx')
true
> cc.isInEuropeanUnion('fr')
false
> cc.isInEuropeanUnion('es')
true
```

I don't see any obvious difference in the data in how Spain and France are different.  Both are made up of "parent" features with `null` geometry and "child" features with `groups` properties.

**Comment by Bonkles** [comment]
Update: I noticed a few interesting facts in the borders.json data file:

Neither spain nor france are directly listed as members of the EU. 
all of Spain's territories are listed as having EU group membership, even though Spain itself does not.
None of France's territories are listed as having EU group membership. France itself, like spain, is also not listed as a direct EU member. 

So why the difference? 

If I modify all of France's territories to also be members of the EU, then the test starts to pass. Somehow, group membership is being synthesized from the 'ground up', considering constituent territories first.
