### ISSUE TITLE
Missing triangle on Swiss border

### ISSUE THREAD

**Issue by haansn08** [ideditor/country-coder#61]
At [geo:47.56982,8.35154](https://www.openstreetmap.org/?mlat=47.56982&mlon=8.35154#map=17/47.56982/8.35154) there is a missing triangle, which should probably be added to the `ch` region.

**Comment by bhousel** [comment]
Found it!  thanks for the report 👍 
<img width="1154" alt="Screen Shot 2022-12-09 at 10 09 37 AM" src="https://user-images.githubusercontent.com/38784/206732659-d276ce55-b2ca-48dd-ba57-680ed2426267.png">
